### ISSUE TITLE
just started getting this error today, was working fine yesterday

### ISSUE THREAD

**Issue by Shiner36** [chanzer0/NFL-DFS-Tools#16]
Running 10000 simulations
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1520.0_x64__qbz5n2kfra8p0\Lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1520.0_x64__qbz5n2kfra8p0\Lib\multiprocessing\pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bshin\Desktop\NFL-DFS-Tools-main\src\nfl_gpp_simulator.py", line 1665, in run_simulation_for_game
    eigenvalues, eigenvectors = np.linalg.eigh(covariance_matrix)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<__array_function__ internals>", line 200, in eigh
  File "C:\Users\bshin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\numpy\linalg\linalg.py", line 1439, in eigh
    _assert_stacked_2d(a)
  File "C:\Users\bshin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\numpy\linalg\linalg.py", line 183, in _assert_stacked_2d
    raise LinAlgError('%d-dimensional array given. Array must be '
numpy.linalg.LinAlgError: 1-dimensional array given. Array must be at least two-dimensional
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\bshin\Desktop\NFL-DFS-Tools-main\src\main.py", line 82, in <module>
    main(sys.argv)
  File "C:\Users\bshin\Desktop\NFL-DFS-Tools-main\src\main.py", line 77, in main
    sim.run_tournament_simulation()
  File "C:\Users\bshin\Desktop\NFL-DFS-Tools-main\src\nfl_gpp_simulator.py", line 1765, in run_tournament_simulation
    results = pool.starmap(self.run_simulation_for_game, game_simulation_params)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1520.0_x64__qbz5n2kfra8p0\Lib\multiprocessing\pool.py", line 375, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1520.0_x64__qbz5n2kfra8p0\Lib\multiprocessing\pool.py", line 774, in get
    raise self._value
numpy.linalg.LinAlgError: 1-dimensional array given. Array must be at least two-dimensional

**Comment by bjungwirth** [comment]
Hey @Shiner36 , you ever figure this out? I've never seen that before, would need to see the input files. Have a feeling it was maybe an issue with matchups?

**Comment by Shiner36** [comment]
It was stokastic boom bust page with some modifications. I uploaded a different projection set and had no issues. Sent from my iPhoneOn Oct 9, 2023, at 2:17 PM, bjungwirth ***@***.***> wrote:﻿
Hey @Shiner36 , you ever figure this out? I've never seen that before, would need to see the input files. Have a feeling it was maybe an issue with matchups?

**Comment by bjungwirth** [comment]
👍 makes sense. closing this issue.
