### ISSUE TITLE
NBA Late Swap

### ISSUE THREAD

**Issue by austinjohnson** [chanzer0/NFL-DFS-Tools#22]
I think I'm missing something with late swap. I'm running `python main.py dk swap 300 1` and I'm getting this error.

```
Traceback (most recent call last):
  File "/Users/aus10/NBA-DFS-Tools/src/main.py", line 95, in <module>
    main(sys.argv)
  File "/Users/aus10/NBA-DFS-Tools/src/main.py", line 26, in main
    swapto = NBA_Late_Swaptimizer(site, num_uniques)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aus10/NBA-DFS-Tools/src/nba_late_swaptimizer.py", line 51, in __init__
    self.load_player_ids(player_path)
  File "/Users/aus10/NBA-DFS-Tools/src/nba_late_swaptimizer.py", line 81, in load_player_ids
    self.ids_to_gametime[row["ID"].replace("-", "#")] = self.player_dict[
                                                        ^^^^^^^^^^^^^^^^^
KeyError: 'GameTime'
```

I've used the DKSalaries file and DKEntries file.

**Comment by bjungwirth** [comment]
hey @austinjohnson sorry for the extremely late reply but can you put this in the NBA repo? i'm gonna close this since it's not relevant to NFL
